@startuml
!pragma layout smetana


'https://plantuml.com/class-diagram
class Main{}

package users{
abstract class User{
- name
- phone
- email
- password
- role - ENUM
}
class Admin{}
class Attendee{
- List<Event> favorites
- List<Event> liked
}
class Organizer{
- accountStatus ENUM
- organizer name
- List<Advert>
}
}

User --|> Organizer
User --|> Admin
User --|> Attendee

class Event {
- title
- description
- Set<startDate>
- Set<endDate>
- time
- price
- category - ENUM
- address
- location
- latitude
- longitude
- imageURL
- organizerPageURL
- sourceType ENUM
}

Event "*"----"*" Attendee
Event "*"--"1" Admin
Event "*"--"1" Organizer
Event "1"--"*" Advert

class Advert{
- placement
- price
- startDate
- endDate
- status ENUM
}
Organizer "1" -- "*" Advert
class Controller{}
Controller -- Main
package daos{
class EventDAO{
CRUD
}
EventDAO --> Event
EventDAO -- Main

class UserDAO{
CRUD
}
UserDAO --> User
UserDAO -- Main

class AdvertDAO{
CRUD
}
AdvertDAO --> Advert
AdvertDAO -- Main
}
@enduml