name: Daily Ticketmaster Sync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Ticket Master Endpoint Trigger
        run: |
          curl -X POST https://seeCphBackend.theisrud.dk/api/v1/events/ticketmaster \
          -H "x-api-key: ${{ secrets.SYNC_SECRET }}"